version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization script

  nugo-backend:
    image: nugomed/backend-nugomed:6df1d7ae23dd9421715a78aad60416c6fea6601a
    env_file:
      - .env
    ports:
      - "8080:8080"
volumes:
  pgdata:
