name: Lint Commit Messages
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  commitlint:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v3
